# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: devScripts
email: kevgary.dev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  devScripts is a resource for developers on the pursuit of knowledge. As one himself, this is where I share the useful technologies and techniques I come across and find relevant to building cool things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  KevGary

# Build settings
markdown: kramdown
